apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host }}
        {{- end }}
      secretName: {{ (index .Values.ingress.tls 0 "secretName") | default "wildcard-duckdns-tls" }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .paths.0.path | default "/" }}
            pathType: {{ .paths.0.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .paths.0.backend.service.name | default $.Values.service.name }}
                port:
                  number: {{ .paths.0.backend.service.port.number | default $.Values.service.port }}
    {{- end }}
