---
- name: Configure AppArmor for Apache (Ubuntu)
  when: ansible_os_family == "Debian"
  block:
    - name: Install AppArmor
      ansible.builtin.apt:
        name: apparmor
        state: present
        update_cache: true

    - name: Copy AppArmor profile
      ansible.builtin.template:
        src: apparmor.conf.j2
        dest: "/etc/apparmor.d/apache2"
        mode: "0o644"
      notify: Restart Apache

- name: Configure SELinux for Apache (Rocky)
  when: ansible_os_family == "RedHat"
  block:
    - name: Set SELinux to Permissive
      ansible.builtin.command: setenforce 0
      changed_when: false

    - name: Make SELinux change persistent
      ansible.builtin.lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=permissive'
      notify: Restart Apache
