---
- name: Install Filebeat (Ubuntu)
  ansible.builtin.apt:
    name: filebeat
    state: present
  when: ansible_os_family == "Debian"

- name: Install Filebeat (Rocky Linux)
  ansible.builtin.dnf:
    name: filebeat
    state: present
  when: ansible_os_family == "RedHat"

- name: Configure Filebeat
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    mode: "0644"
  notify: Restart Filebeat

- name: Enable and start Filebeat
  ansible.builtin.systemd:
    name: filebeat
    enabled: true
    state: started
