---
- name: Install Fail2Ban (Ubuntu)
  ansible.builtin.apt:
    name: fail2ban
    state: present
  when: ansible_os_family == "Debian"

- name: Install Fail2Ban (Rocky Linux)
  ansible.builtin.dnf:
    name: fail2ban
    state: present
  when: ansible_distribution == "Rocky" and ansible_distribution_major_version in ["8", "9"]

- name: Copy Fail2Ban config
  ansible.builtin.copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    mode: "0644"
  notify: Restart Fail2Ban
