---
- name: Install firewall packages on Ubuntu
  apt:
    name: ufw
    state: present
  when: ansible_os_family == "Debian"

- name: Install firewall packages on Rocky
  dnf:
    name: firewalld
    state: present
  when: ansible_os_family == "RedHat"

- name: Configure UFW on Ubuntu (allow HTTP, HTTPS, SSH)
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "22"
    - "80"
    - "443"
  when: ansible_os_family == "Debian"

- name: Enable UFW
  ufw:
    state: enabled
  when: ansible_os_family == "Debian"

- name: Configure Firewalld on Rocky
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "ssh"
    - "http"
    - "https"
  when: ansible_os_family == "RedHat"

- name: Reload Firewalld
  firewalld:
    state: reloaded
    immediate: true
  when: ansible_os_family == "RedHat"
