---
- name: Install firewall packages on Ubuntu
  ansible.builtin.apt:
    name: ufw
    state: present
  when: ansible_os_family == "Debian"

- name: Install firewall packages on Rocky
  ansible.builtin.dnf:
    name: firewalld
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution_version in ["8", "9"]

- name: Configure UFW on Ubuntu (allow HTTP, HTTPS, SSH)
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "22"
    - "80"
    - "443"
  when: ansible_os_family == "Debian"

- name: Enable UFW
  community.general.ufw:
    state: enabled
  when: ansible_os_family == "Debian"

- name: Configure Firewalld on Rocky
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "ssh"
    - "http"
    - "https"
  when: ansible_os_family == "RedHat" and ansible_distribution_version in ["8", "9"]

- name: Reload Firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: false
  when: ansible_os_family == "RedHat" and ansible_distribution_version in ["8", "9"]
