---
- name: Configure Firewall (Ubuntu)
  when: ansible_os_family == "Debian"
  block:
    - name: Allow Apache through UFW
      community.general.ufw:
        rule: allow
        name: "Apache Full"

    - name: Enable UFW
      community.general.ufw:
        state: enabled

- name: Configure Firewall (Rocky)
  when: ansible_os_family == "RedHat"
  block:
    - name: Allow Apache through Firewalld
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled

    - name: Allow HTTPS through Firewalld
      ansible.posix.firewalld:
        service: https
        permanent: true
        state: enabled

    - name: Reload Firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
