---
- name: Apply Security Hardening (Ubuntu)
  when: ansible_os_family == "Debian"
  block:
    - name: Copy security.conf
      ansible.builtin.template:
        src: security.conf.j2
        dest: "/etc/apache2/conf-available/security.conf"
        mode: "0o644"
      notify: Restart Apache

    - name: Enable security module
      ansible.builtin.command: a2enconf security
      changed_when: false
      notify: Restart Apache

- name: Apply Security Hardening (Rocky)
  when: ansible_os_family == "RedHat"
  block:
    - name: Copy security.conf
      ansible.builtin.template:
        src: security.conf.j2
        dest: "/etc/httpd/conf.d/security.conf"
        mode: "0o644"
      notify: Restart Apache
