---
- name: Install Apache (Ubuntu)
  when: ansible_os_family == "Debian"
  block:
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true

    - name: Ensure Apache is started and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

- name: Install Apache (Rocky)
  when: ansible_os_family == "RedHat"
  block:
    - name: Install Apache
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Ensure Apache is started and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
