---
- name: Detect OS family
  set_fact:
    os_family: "{{ ansible_os_family }}"
    os_version: "{{ ansible_distribution_major_version }}"

- name: Install Apache (Ubuntu)
  apt:
    name: apache2
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install Apache (Rocky)
  dnf:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure Apache is started and enabled
  systemd:
    name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    state: started
    enabled: true
