---
- name: Install Python 3.9 on Rocky Linux 8
  when: ansible_os_family == "Rocky" and ansible_distribution_version is version("8", "==")
  block:
    - name: Install Python 3.9
      ansible.builtin.dnf:
        name: python39
        state: present

    - name: Set Python 3.9 as default
      ansible.builtin.command: alternatives --set python /usr/bin/python3.9
      changed_when: false

    - name: Verify Python version
      ansible.builtin.command: python --version
      register: python_version_output
      changed_when: false

    - name: Show Python version
      ansible.builtin.debug:
        msg: "Python version set to {{ python_version_output.stdout }}"
