---
- name: Detectar distribución
  set_fact:
    os_family: "{{ ansible_os_family }}"
    os_version: "{{ ansible_distribution_major_version }}"

- name: Instalar paquetes en Ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-security2
      - ufw
      - python3-certbot-apache
      - filebeat
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Instalar paquetes en Rocky Linux
  dnf:
    name:
      - httpd
      - mod_security
      - firewalld
      - certbot
      - filebeat
    state: present
  when: ansible_os_family == "RedHat"
