---
- name: Detect OS family
  ansible.builtin.set_fact:
    os_family: "{{ ansible_os_family }}"
    os_version: "{{ ansible_distribution_major_version }}"

- name: Install Apache (Ubuntu)
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install Apache (Rocky)
  ansible.builtin.dnf:
    name: httpd
    state: present
  when: ansible_os_family == "Rocky" and ansible_distribution_version in ["8", "9"]

- name: Ensure Apache is started and enabled
  ansible.builtin.systemd:
    name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    state: started
    enabled: true
