---
- name: Install Python Dependencies
  block:
    - name: Install Python3 (Ubuntu)
      ansible.builtin.apt:
        name: python3
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Install Python3 (Rocky)
      ansible.builtin.dnf:
        name: python3
        state: present
      when: ansible_os_family == "RedHat"
