---
- name: Configure Logging for Apache (Ubuntu)
  when: ansible_os_family == "Debian"
  block:
    - name: Copy logrotate configuration
      ansible.builtin.template:
        src: logging.conf.j2
        dest: "/etc/logrotate.d/apache2"
        mode: "0o644"

    - name: Restart Logrotate
      ansible.builtin.service:
        name: logrotate
        state: restarted

- name: Configure Logging for Apache (Rocky)
  when: ansible_os_family == "RedHat"
  block:
    - name: Copy logrotate configuration
      ansible.builtin.template:
        src: logging.conf.j2
        dest: "/etc/logrotate.d/httpd"
        mode: "0o644"

    - name: Restart Logrotate
      ansible.builtin.service:
        name: logrotate
        state: restarted
