---
- name: Restart Apache
  systemd:
    name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    state: restarted

- name: Restart Logstash
  systemd:
    name: logstash
    state: restarted

- name: Restart Filebeat
  systemd:
    name: filebeat
    state: restarted
