services:
  wildfly:
    image: docker.io/bitnami/wildfly:35
    ports:
      - '8080:8080'
      - '9990:9990'
    volumes:
      - './standalone.xml:/bitnami/wildfly/standalone/configuration/standalone.xml'
    environment:
      - WILDFLY_PASSWORD=password
      - JBOSS_BIND_ADDRESS=0.0.0.0
      - JBOSS_BIND_ADDRESS_MANAGEMENT=0.0.0.0

volumes:
  wildfly_data:
    driver: local
