services:
  wildfly:
    image: docker.io/bitnami/wildfly:35
    ports:
      - '8080:8080'
      - '9990:9990'
    volumes:
      - './deployments:/bitnami/wildfly/standalone/deployments'
      - './logs:/bitnami/wildfly/standalone/log'
      - './config:/bitnami/wildfly/standalone/configuration'
    environment:
      - WILDFLY_USERNAME=admin
      - WILDFLY_PASSWORD=password
      - JBOSS_BIND_ADDRESS=0.0.0.0
      - JBOSS_BIND_ADDRESS_MANAGEMENT=0.0.0.0

volumes:
  wildfly_data:
    driver: local
