services:
  wildfly:
    image: docker.io/bitnami/wildfly:35
    ports:
      - '8080:8080'
      - '9990:9990'
    volumes:
      - './config/standalone.xml:/bitnami/wildfly/standalone/configuration/standalone.xml'
    environment:
      - WILDFLY_PASSWORD=password

volumes:
  wildfly_data:
    driver: local
