services:
  wildfly:
    image: my-wildfly:latest
    container_name: wildfly_secure
    build: .
    restart: always
    environment:
      WILDFLY_ADMIN_USER: "${WILDFLY_ADMIN_USER}"
      WILDFLY_ADMIN_PASS: "${WILDFLY_ADMIN_PASS}"
      JAVA_OPTS: "-Xms512m -Xmx1024m -XX:+UseG1GC"
    ports:
      - "8080:8080"    # HTTP
      - "8443:8443"    # HTTPS
      - "9990:9990"    # Management Interface (Restringido)
    volumes:
      - ./data/deployments:/opt/wildfly/standalone/deployments
      - ./data/logs:/opt/wildfly/standalone/log
      - ./data/config:/opt/wildfly/standalone/configuration
      - ./certs:/etc/pki/tls/private
    entrypoint: ["/scripts/entrypoint.sh"]
