namespace: middleware

replicaCount: 2

image:
  repository: httpd
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  name: apache-service
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: apache
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: apache.helmgolmolab.duckdns.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - apache.helmgolmolab.duckdns.org
      secretName: wildcard-duckdns-tls
