namespace: middleware

replicaCount: 2

image:
  repository: httpd
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  name: apache-service
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - apache.helmgolmolab.duckdns.org
  tls:
    - hosts:
        - apache.helmgolmolab.duckdns.org
      secretName: wildcard-duckdns-tls
