namespace: middleware

replicaCount: 2

image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  name: nginx-service
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: nginx.helmgolmolab.duckdns.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - nginx.helmgolmolab.duckdns.org
      secretName: wildcard-duckdns-tls
