services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APACHE_VERSION: ${APACHE_VERSION}
    container_name: apache2_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./config/extra/:/usr/local/apache2/conf/extra/:ro
      - ./www:/usr/local/apache2/htdocs
      - ./certs:/etc/apache2/ssl
    environment:
      - TZ=${TIMEZONE}
      - ENABLE_SSL=${ENABLE_SSL}
      - SERVER_NAME=apache.local
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
