services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache2_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./config/extra/:/usr/local/apache2/conf/extra/:ro
      - ./www:/usr/local/apache2/htdocs
      - ./logs:/usr/local/apache2/logs
      - ./certs:/etc/apache2/ssl
    environment:
      TZ: "Europe/Madrid"
      ENABLE_SSL: "false"
      SERVER_NAME: "apache.local"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
