services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache2_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./config/extra/:/usr/local/apache2/conf/extra/:ro
      - ./www:/usr/local/apache2/htdocs
      - ./logs:/usr/local/apache2/logs
    environment:
      TZ: "Europe/Madrid"
      SERVER_NAME: "apache.local"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
