namespace: middleware

replicaCount: 2

image:
  repository: store/oracle/weblogic
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  name: weblogic-service
  type: ClusterIP
  port: 7001

ingress:
  enabled: true
  ingressClassName: weblogic
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: weblogic.helmgolmolab.duckdns.org
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: weblogic-service
              port:
                number: 80
  tls:
    - hosts:
        - weblogic.helmgolmolab.duckdns.org
      secretName: wildcard-duckdns-tls
