apiVersion: v1
kind: Service
metadata:
  name: weblogic
  namespace: middleware
spec:
  selector:
    app: weblogic
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 7001
  type: ClusterIP
