services:
  tomcat:
    image: docker.io/bitnami/tomcat:9.0.98
    ports:
      - '8080:8080'
    volumes:
      - './deployments:/opt/bitnami/tomcat/webapps'
      - './logs:/opt/bitnami/tomcat/logs'
      - './config:/opt/bitnami/tomcat/conf'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - TOMCAT_USERNAME=admin
      - TOMCAT_PASSWORD=SuperPasswordSegura123
      - TOMCAT_ALLOW_REMOTE_MANAGEMENT=yes
      - TOMCAT_ENABLE_MGMT_APPS=yes

volumes:
  tomcat_data:
    driver: local
