apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail.yaml: |
    scrape_configs:
      - job_name: "middleware-logs"
        static_configs:
          - targets:
              - localhost
            labels:
              job: "middleware"
              __path__: "/var/log/*.log"
