- name: Deploy main nginx.conf
  ansible.builtin.template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Restart Nginx

- name: Deploy load balancer configuration
  ansible.builtin.template:
    src: "load-balancer.conf.j2"
    dest: "/etc/nginx/conf.d/load-balancer.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Restart Nginx

- name: Ensure SSL directory exists
  ansible.builtin.file:
    path: /etc/nginx/ssl
    state: directory
    owner: nginx
    group: nginx
    mode: "0755"

- name: Ensure required Python modules are installed
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - packaging
    - cryptography

- name: Generate self-signed SSL certificate
  community.crypto.x509_certificate:
    path: "{{ nginx_ssl_certificate }}"
    privatekey_path: "{{ nginx_ssl_certificate_key }}"
    csr_path: "{{ nginx_ssl_csr }}"
    provider: selfsigned
    owner: nginx
    group: nginx
    mode: "0600"
  notify: Restart Nginx

- name: Ensure correct permissions for SSL keys
  ansible.builtin.file:
    path: "{{ nginx_ssl_certificate_key }}"
    mode: "0600"

- name: Deploy SSL configuration
  ansible.builtin.template:
    src: "ssl.conf.j2"
    dest: "/etc/nginx/conf.d/ssl.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Restart Nginx
