apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: {{ .Values.service.type }}
