[ALL]
nginx1 ansible_host=192.168.1.121
server1 ansible_host=192.168.1.123
server2 ansible_host=192.168.1.124

[nginx-lb]
nginx1 ansible_host=192.168.1.121

[Datacenter1]
server1 ansible_host=rocky9vm03

[Datacenter2]
server2 ansible_host=rocky9vm04
