---
- name: Configure Dynamic motd
  hosts: all
  become: true

  roles:
    - { role: motd, tags: ["motd"] }
    - { role: tomcat, tags: ["tomcat"] }
    - { role: nginx, tags: ["nginx"] }
    - { role: tomcat-hardening, tags: ["tomcat-hardening"] }
    - { role: nginx-revproxy, tags: ["revproxy"] }            
