services:
  nginx:
    image: 'docker.io/bitnami/nginx:1.27.4'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './web:/app'
      - './config/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf'
      - './sites:/opt/bitnami/nginx/conf/server_blocks'
      - './logs/access.log:/opt/bitnami/nginx/logs/access.log'
      - './logs/error.log:/opt/bitnami/nginx/logs/error.log'

volumes:
  nginx_data:
    driver: local
