services:
  nginx:
    build:
      context: .
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    container_name: nginx_hardened
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_network
    volumes:
      - ./nginx/conf:/etc/nginx
      - ./nginx/logs:/var/log/nginx
      - ./nginx/html:/var/www/html
      - ./nginx/certs:/etc/ssl/certs
    environment:
      - TZ=UTC
      - NGINX_VERSION=${NGINX_VERSION}

networks:
  nginx_network:
    driver: bridge
