services:
  nginx:
    image: 'docker.io/bitnami/nginx:1.27.4'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './config:/opt/bitnami/nginx/conf'
      - './sites:/opt/bitnami/nginx/conf/server_blocks'
      - './logs:/opt/bitnami/nginx/logs'
      - ./web:/app

volumes:
  nginx_data:
    driver: local
