services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_hardened
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_network
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/:/etc/nginx/conf.d/:ro
    environment:
      - TZ=${TIMEZONE}
      - ENABLE_SSL=${ENABLE_SSL}
      - SERVER_NAME=${ENABLE_SSL}

networks:
  nginx_network:
    driver: bridge
