services:
  nginx:
    build:
      context: .
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    container_name: nginx_hardened
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_network
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/security.conf:/etc/nginx/conf.d/security.conf:ro
      - ./nginx/conf/hardening.conf:/etc/nginx/conf.d/hardening.conf:ro
      - ./nginx/conf/logging.conf:/etc/nginx/conf.d/logging.conf:ro
      - ./nginx/conf/firewall.conf:/etc/nginx/conf.d/firewall.conf:ro
