services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_hardened
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_network
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro

networks:
  nginx_network:
    driver: bridge
